### ISSUE TITLE
Docker 服务设置为开机自启

### ISSUE THREAD

**Issue by eliu** [choerodon/kubeadm-ansible#23]
可否在安装 Docker 的时候将 Docker 服务设置为开机自启动呢？比如遇到服务器宕机或者重启等等情况下，Docker是无法自动启动的。

Ansible task: 

```yaml
---
- name: Enable docker service
  service: docker
    enabled: yes
```
